import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";
import { themes as prismThemes } from "prism-react-renderer";

// FlowPlan documentation site (Docusaurus, MIT). Content is read directly from
// the repository's docs/ folder — the single source of truth — and the Engine
// API pages under docs/engine-api/ are generated by TypeDoc (see typedoc.json).
// Built and published to GitHub Pages by .github/workflows/docs.yml.
const config: Config = {
  title: "FlowPlan",
  tagline: "Cell & material-flow planning for manufacturing",
  favicon: "img/favicon.svg",

  // GitHub Pages project site: https://<org>.github.io/<repo>/
  url: "https://jakobgabriel.github.io",
  baseUrl: "/genai4floorplans/",
  organizationName: "jakobgabriel",
  projectName: "genai4floorplans",
  trailingSlash: false,

  // The specs deliberately link to source files (../packages/...) and to each
  // other; warn rather than fail the build on links that don't resolve.
  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",

  // Treat .md as CommonMark (only .mdx is parsed as MDX), so the existing docs
  // — which contain raw <, { and € — build without MDX escaping errors.
  markdown: { format: "detect" },

  i18n: { defaultLocale: "en", locales: ["en"] },

  presets: [
    [
      "classic",
      {
        docs: {
          path: "../docs",
          routeBasePath: "docs",
          sidebarPath: "./sidebars.ts",
          editUrl: "https://github.com/jakobgabriel/genai4floorplans/edit/main/",
        },
        blog: false,
        theme: { customCss: "./src/css/custom.css" },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: "FlowPlan",
      items: [
        { type: "docSidebar", sidebarId: "docsSidebar", position: "left", label: "Docs" },
        { to: "/docs/line-planner-spec", label: "Specification", position: "left" },
        { to: "/docs/audit-log-shopfloor-review", label: "Quality audit", position: "left" },
        { to: "/docs/api/core", label: "Core API", position: "left" },
        { href: "pathname:///rest-api/", label: "REST API", position: "left" },
        { href: "https://github.com/jakobgabriel/genai4floorplans", label: "GitHub", position: "right" },
      ],
    },
    footer: {
      style: "dark",
      copyright:
        "Generated from the repository's canonical docs/ and the @flowplan/core engine JSDoc.",
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ["bash", "json", "typescript"],
    },
    colorMode: { respectPrefersColorScheme: true },
  } satisfies Preset.ThemeConfig,
};

export default config;
