import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Curated sidebar over the repo's docs/ (ids are filenames without extension).
// The Engine API subtree is autogenerated from the TypeDoc output in
// docs/engine-api/ (produced by `npm run docs:api` before every build).
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Introduction",
      collapsed: false,
      items: ["walkthrough"],
    },
    {
      type: "category",
      label: "Specification",
      collapsed: false,
      items: [
        "line-planner-spec",
        "flowplanspec",
        "spec-alignment",
        "workload-model",
        "concept-model",
        "cell-shapes",
        "lifecycle-cases-implementation",
      ],
    },
    {
      type: "category",
      label: "Quality & gaps",
      collapsed: false,
      items: [
        "audit-log-shopfloor-review",
        "product-gap-analysis",
        "carbon-gap-analysis",
        "ROADMAP",
        "HANDOVER",
      ],
    },
    {
      type: "category",
      label: "Engineering",
      collapsed: true,
      items: [
        "erd",
        "optimize-layout",
        "concept-generation",
        "planner",
        "local-database",
        "postgres-everything-plan",
      ],
    },
    {
      type: "category",
      label: "Core API (@flowplan/core)",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "api/core" }],
    },
    {
      type: "category",
      label: "Web API (@flowplan/web)",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "api/web" }],
    },
    {
      type: "link",
      label: "REST API (server)",
      href: "pathname:///rest-api/",
    },
  ],
};

export default sidebars;
