import type { ReactNode } from "react";
import Link from "@docusaurus/Link";
import Layout from "@theme/Layout";

// Minimal landing page. Everything substantive lives in the synced docs and the
// generated API reference; this is just a signpost.
export default function Home(): ReactNode {
  return (
    <Layout title="FlowPlan" description="Cell & material-flow planning for manufacturing">
      <main style={{ maxWidth: 820, margin: "0 auto", padding: "4rem 1.5rem" }}>
        <h1 style={{ fontSize: "2.4rem", marginBottom: "0.5rem" }}>FlowPlan</h1>
        <p style={{ fontSize: "1.2rem", opacity: 0.85 }}>
          Rate a production cell across flow, balance, takt, ergonomics and automation — and see a
          scored, buildable improved layout. No CAD, no backend required to start.
        </p>
        <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap", margin: "1.75rem 0" }}>
          <Link className="button button--primary button--lg" to="/docs/walkthrough">
            Walkthrough
          </Link>
          <Link className="button button--secondary button--lg" to="/docs/line-planner-spec">
            Governing specification
          </Link>
          <Link className="button button--secondary button--lg" to="/docs/audit-log-shopfloor-review">
            Quality audit
          </Link>
          <Link className="button button--secondary button--lg" to="/docs/engine-api">
            Engine API
          </Link>
        </div>
        <hr />
        <p style={{ opacity: 0.8 }}>
          This site is generated automatically: the narrative pages are read directly from the
          repository&rsquo;s <code>docs/</code> folder (the single source of truth), the Engine API is
          generated by TypeDoc from the <code>@flowplan/core</code> JSDoc, and both are built and
          published to GitHub Pages on every push to <code>main</code>.
        </p>
      </main>
    </Layout>
  );
}
